project_name: reddit-img-dl

build:
  env:
    - CGO_ENABLED=1

  main: ./
  binary: reddit-img-dl
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
